### ISSUE TITLE
Implement quality-of-life commands

### ISSUE THREAD

**Issue by MikkelPaulson** [initiative-sh/initiative.sh#53]
* [x] #56
* [x] ~New command: help~ Resolved by #56 
* [x] ~New command: news~ Implemented as `changelog` in #56
* [x] ~New command: tutorial~ Split off as #66
